version: '3'
services:
  selenium-hub:
    image: selenium/hub:nightly
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:nightly
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g
    networks:
        - grid

networks:
  grid:
    driver: bridge

